# Generated by Django 3.1.2 on 2024-10-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
