# Generated by Django 3.1.2 on 2024-10-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Planta un Árbol', 'Planta un Árbol'), ('Herramientas', 'Herramientas'), ('Desechos', 'Desechos')], max_length=100)),
                ('comuna', models.CharField(max_length=100, null=True)),
                ('tipo_arbol', models.CharField(choices=[('Roble', 'Roble'), ('Árbol de Neem', 'Árbol de Neem'), ('Cedro', 'Cedro')], max_length=100)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'donacion',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='donacion',
            constraint=models.UniqueConstraint(fields=('opcion', 'comuna', 'tipo_arbol', 'cantidad'), name='unique_donation'),
        ),
    ]
